---
name: Testing

env:
  TZ: Asia/Shanghai

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

on:
  push: # If you define neither tags(-ignore) nor branches(-ignore), the workflow will run for either branches or tags.
    paths:
      - 'action.yml'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

      - name: Dump flattened GitHub actions contexts
        uses: ./

      - name: Dump with sep
        id: more
        uses: ./
        with:
          sep: ' = '
...